services:
  server:
    image: wink:latest
    command:
      - /bin/sh
      - -c
      - |
        ls build/samples/
        ./build/src/WinkServer serve -a 10.0.0.2:42000 build/samples/
    expose:
      - "42000:42000/udp"
      - "64000:64000/udp"
      - "64001:64001/udp"
      - "64002:64002/udp"
      - "64003:64003/udp"
      - "64004:64004/udp"
    networks:
      winknet:
        ipv4_address: 10.0.0.2
    working_dir: /Wink

  client:
    image: wink:latest
    command:
      - /bin/sh
      - -c
      - |
        sleep 1
        ./build/src/Wink start -a 10.0.0.4:42001 -f true time/After 10.0.0.2:64000
        ./build/src/Wink start -a 10.0.0.4:42001 -f true time/At 10.0.0.2:64001
        ./build/src/Wink start -a 10.0.0.4:42001 time/StopWatch 10.0.0.2:64002
        ./build/src/Wink send 10.0.0.2:64002 idle
        ./build/src/Wink send 10.0.0.2:64002 start
        ./build/src/Wink send 10.0.0.2:64002 stop
        ./build/src/Wink send 10.0.0.2:64002 start
        sleep 1
        ./build/src/Wink send 10.0.0.2:64002 stop
        ./build/src/Wink send 10.0.0.2:64002 exit
        ./build/src/Wink start -a 10.0.0.4:42001 time/Ticker:fast 10.0.0.2:64003 2
        ./build/src/Wink start -a 10.0.0.4:42001 time/Ticker:slow 10.0.0.2:64004 20
    expose:
      - "42001:42001/udp"
    networks:
      winknet:
        ipv4_address: 10.0.0.4
    working_dir: /Wink

networks:
  winknet:
    driver: bridge
    internal: true
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
