name: Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: docker build . -t wink:latest
      run: DOCKER_BUILDKIT=0 docker build . -t winkrpi:latest -f samples/rpi/Dockerfile
